### ISSUE TITLE
Template Version [hash7/8]

### ISSUE THREAD

**Issue by marcoris** [fabiospampinato/vscode-bump#6]
Hi Fabio
excellent plugin you have made.
I have an Issue about the bump.templates.version with hash7/8.
I.e. 
`"bump.templates.version": "#[[version]](https://bitbucket.org/MYNAME/commits/[hash8]) ([version_date])"`
Should output the correct hash in the link, but it dont do it. In the text is the correct hash. I also tested [hash7] and [hash8]. 

In the bump.templates.commit it is outputting the correct hash.
`"bump.templates.commit": "- [message] ([[hash7]](https://bitbucket.org/MYNAME/commits/[hash7]))"`

Is it also possible to check if the bump was a major and then style the template different? So i can add one # in major bump and two # for minor bump and so on?

Thx

**Comment by fabiospampinato** [comment]
> Should output the correct hash in the link, but it dont do it.

I'll have to think more about this, but since we update the changelog before making the bump commit I don't think you can do what you describe.

> Is it also possible to check if the bump was a major and then style the template different?

I could add support for this, but I'm not sure if it would be that useful, after all how often do you make major releases? Right now you should manually modify the changelog and eventually amend the bump commit.

**Comment by marcoris** [comment]
Ok thanks for your response.

**Comment by fabiospampinato** [comment]
On a second thought I think there are some good features that should be implemented: 

- GitHub tokens https://github.com/fabiospampinato/vscode-bump/issues/8
- Increment overrides https://github.com/fabiospampinato/vscode-bump/issues/7

I'm closing this issue in favor of them.
